baseURL = 'http://mattherix.github.io/'
title = 'Mattherix blog'
theme = ['PaperMod', 'hugo-loremipsum']
copyright = 'CC-BY-SA {year}'

defaultContentLanguage = 'fr'
[languages]
  [languages.en]
    title = "Mattherix's Blog"
    weight = 1
  [languages.fr]
    title = 'Blog de Mattherix'
    weight = 2
